name: Update Data

on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: '${{ secrets.GIT_SSH_KEY }}'
    - name: Setup
      run: |
        set -xe
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        pip3 install lxml
    - run: python3 tools/csv-to-sqlite.py
    - run: python3 tools/dump-series-first.py
    - run: python3 tools/dump-shiten-ids-from-snapshot.py
    - run: python3 tools/sqlite-to-csv.py
    - name: Upload
      run: |
        echo "$(date +"%Y-%m-%dT%H:%M:%SZ")" > last_update_by_ci.txt
        git add -A
        git commit -m "Update Data ($(date +"%Y-%m-%dT%H:%M:%SZ"))"
        git fetch
        git rebase origin/master
        git push origin master
